inputs:
  repo:
    requred: true
    type: string
    default: oh-my-posh-install
  file:
    requred: true
    type: string
    default: "oh-my-posh-install.ps1 README.md"
  owner:
    requred: true
    type: string
    default: zsvs
  target_branch:
    requred: true
    type: string
    default: test
  old_version:
    required: true
    type: string
    default: "posh"
  new_version:
    required: true
    type: string
    default: "Deprecated"