name: 'Update file content'

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
        default: TestUpdateContentAction
      file:
        required: true
        type: string
        default: "test-data.yaml"
      owner:
        required: true
        type: string
        default: zsvs
      target_branch:
        required: true
        type: string
        default: test
      new_value:
        required: true
        type: string
        default: "1.0.0"
      parent_key:
        required: true
        type: string
        default: "front"
      child_key:
        required: true
        type: string
        default: "tag"
      pr_title:
        required: true
        type: string
        default: "Update tag value"
      pr_message:
        required: true
        type: string
        default: "This tag value has been updated by GH action!"

jobs:

  TestOctokit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v2
      name: Node installation
      with:
        node-version: 16

    - name: Get Branch with octo
      uses: zsvs/UpdateFileContent@v1.0.0
      with:
        repo: ${{ inputs.repo }}
        owner: ${{ inputs.owner }}
        file: ${{ inputs.file }}
        new_value: ${{ inputs.new_value}}
        target_branch: ${{ inputs.target_branch }}
        parent_key: ${{ inputs.parent_key}}
        child_key: ${{ inputs.child_key }}
        pr_title: ${{ inputs.pr_title }}
        pr_message: ${{ inputs.pr_message }}
        github_tkn: ${{ secrets.PAT_TOKEN }}