name: 'Update file content'

on:
  workflow_dispatch:
    inputs:
      repo:
        requred: true
        type: string
        default: oh-my-posh-install
      file:
        requred: true
        type: string
        default: "oh-my-posh-install.ps1 README.md"
      owner:
        requred: true
        type: string
        default: zsvs
      target_branch:
        requred: true
        type: string
        default: test
      old_version:
        required: true
        type: string
        default: "posh"
      new_version:
        required: true
        type: string
        default: "Deprecated"



jobs:

  TestOctokit:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-node@v2
      name: Node installation
      with:
        node-version: 14
# TODO Change zsvs/OctokitAction@main to actual action

    - name: Get Branch with octo
      uses: zsvs/UpdateFileContent@main
      with:
        repo: ${{ inputs.repo }}
        owner: ${{ inputs.owner }}
        file: ${{ inputs.file }}
        old_version : ${{ inputs.old_version }}
        new_version: ${{ inputs.new_version}}
        target_branch: ${{ inputs.target_branch }}
        github_tkn: ${{ secrets.PAT_TOKEN }}